insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('323617733-0', '3210', 'Bunny Ashtonhurst', 'Hercules', 'algorithm', 7, 'Action|Adventure', 'Langosh, Carter and Steuber', 2003, 'Guaraní', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/216x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('387004866-2', '56', 'Eula Sellack', 'Bullet for the General, A (Quién Sabe?)', 'firmware', 5, 'Western', 'Moen-Walsh', 1985, 'Moldovan', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/181x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('777083973-4', '905', 'Maryellen Kennedy', 'Edward, My Son', 'capacity', 2, 'Drama', 'Braun Group', 2009, 'Assamese', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('325413665-9', '47', 'Renee Wastell', 'Ju Dou', 'standardization', 5, 'Drama', 'Skiles Group', 2010, 'Pashto', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'http://dummyimage.com/127x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('525053905-X', '0130', 'Wally Bullene', 'Summer Holiday', 'Fundamental', 6, 'Musical', 'Huels Group', 2008, 'Gagauz', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/127x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('665034011-1', '13243', 'Gert Vardey', 'Life and Death of Peter Sellers, The', 'Multi-tiered', 2, 'Comedy|Drama', 'Paucek-Koss', 2009, 'Mongolian', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/220x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('833487277-1', '69', 'Glynis Lourens', 'Better Luck Tomorrow', 'frame', 1, 'Crime|Drama', 'Reynolds Inc', 2009, 'Macedonian', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'http://dummyimage.com/246x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('479018441-2', '26', 'Leigha Harrington', 'Wedding Night, The', 'holistic', 6, 'Drama|Romance', 'Douglas, Hirthe and Hoppe', 2012, 'Spanish', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/153x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('029634252-1', '7', 'Fidelity Crewe', 'Five and Ten', 'circuit', 4, 'Romance', 'O''Connell-Olson', 2012, 'Icelandic', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/102x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('597527458-3', '04707', 'Isidor Calderbank', 'Place in the Sun, A', 'dedicated', 8, 'Drama|Romance', 'Hamill, Wisoky and Satterfield', 2006, 'Portuguese', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/140x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('741454884-8', '3100', 'Ardelle Chetter', 'Call Northside 777', 'workforce', 6, 'Crime|Drama|Film-Noir', 'Cartwright, Buckridge and Orn', 1991, 'Belarusian', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('312386868-0', '269', 'Muffin Verne', 'Death Warrant', 'installation', 7, 'Action', 'Greenfelder, Weimann and Effertz', 2013, 'Hebrew', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'http://dummyimage.com/193x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('344480892-5', '76', 'Vickie Mourgue', 'American Ninja 2: The Confrontation', 'application', 5, 'Action|Adventure', 'Watsica, Ernser and Pagac', 1996, 'Indonesian', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/154x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('129987040-6', '304', 'Tiffanie Huston', 'Hangin'' with the Homeboys', 'context-sensitive', 9, 'Comedy|Drama', 'Treutel Inc', 2005, 'Czech', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/241x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('618377681-5', '2220', 'Buddie Speller', 'Cameraman''s Revenge, The (Mest kinematograficheskogo operatora)', 'Configurable', 3, 'Animation|Comedy', 'Hermiston Inc', 1968, 'Swedish', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/187x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('829215484-1', '354', 'Sheela Guichard', 'Congo', '24 hour', 9, 'Action|Adventure|Mystery|Sci-Fi', 'Christiansen-Stehr', 2008, 'Bengali', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.

Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'http://dummyimage.com/122x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('193222607-9', '1277', 'Theodosia Newlove', 'My Louisiana Sky', 'human-resource', 7, 'Drama', 'Moen, Rutherford and Ratke', 2006, 'Dhivehi', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/133x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('764049270-X', '01377', 'Bing McMurty', 'Space Pirate Captain Harlock', 'attitude', 3, 'Animation|Sci-Fi', 'Kirlin-Wolf', 2008, 'Gujarati', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/124x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('623654511-1', '27156', 'Loreen Emblin', 'Huckleberry Finn', 'Switchable', 1, 'Adventure|Musical', 'Predovic LLC', 1995, 'Dhivehi', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/182x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('529595271-1', '39', 'Winn Olivelli', 'Air I Breathe, The', 'complexity', 5, 'Crime|Drama|Romance|Thriller', 'Zemlak, Jerde and Herman', 1990, 'English', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/212x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('264889581-7', '980', 'Hally Urvoy', 'Savannah', 'flexibility', 10, 'Drama|Romance', 'Swift and Sons', 2010, 'Macedonian', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/104x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('945856890-0', '1127', 'Junia Boath', 'My Favorite Brunette', 'clear-thinking', 5, 'Comedy|Mystery', 'Mertz-Harris', 1997, 'Kazakh', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://dummyimage.com/175x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('796017402-4', '524', 'Terrell Kersey', 'Lights Out', 'success', 4, 'Drama|Mystery|Thriller', 'Steuber-Osinski', 1993, 'Persian', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/246x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('793922178-7', '22682', 'Antonius Dudbridge', 'Mom and Dad Save the World', 'Adaptive', 6, 'Comedy|Sci-Fi', 'Schuster Group', 1998, 'Dzongkha', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/222x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('579464487-7', '61191', 'Robinett Killby', 'Enemy Within, The (O ehthros mou)', 'Enhanced', 1, 'Drama', 'Konopelski Inc', 2009, 'Mongolian', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/162x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('131388473-1', '72', 'Tanhya Element', 'Blindman', 'firmware', 3, 'Western', 'Hauck-Predovic', 1990, 'Assamese', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/124x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('776946735-7', '33358', 'Pancho Fayer', 'Angelus', 'Face to face', 5, 'Comedy|Drama', 'Greenholt, Satterfield and Lubowitz', 2001, 'English', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/191x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('117560753-3', '8', 'Elmo Mortell', 'Taken', 'stable', 10, 'Sci-Fi', 'Quigley-Greenfelder', 2003, 'Persian', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/168x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('147307406-1', '8', 'Beryle Lapthorn', 'Smokey and the Bandit II', 'parallelism', 2, 'Action|Comedy', 'Turcotte-Rodriguez', 2003, 'Zulu', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/114x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('364744019-1', '8774', 'Spenser Pridgeon', 'Code Name: The Cleaner', 'bottom-line', 3, 'Action|Comedy|Crime', 'Johns LLC', 2010, 'Tajik', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/169x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('647612104-9', '889', 'Lemmy Hoggetts', 'Sex Is Comedy', 'Balanced', 8, 'Comedy|Drama|Romance', 'Bednar-Rowe', 2005, 'Catalan', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/171x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('691615337-7', '05187', 'Stoddard Batchley', 'Super Cops, The', 'Advanced', 3, 'Action|Comedy|Crime|Drama|Thriller', 'Hilll-Simonis', 1997, 'Dzongkha', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/229x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('458754615-1', '62', 'Barnard Clempton', 'Watching the Detectives', 'methodology', 10, 'Comedy|Romance', 'Conroy LLC', 1997, 'Bulgarian', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/216x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('841925236-0', '5', 'Daloris Dinley', 'Helicopter String Quartet', 'Persevering', 7, 'Documentary', 'Muller-Mann', 2008, 'Gujarati', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/189x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('318711517-9', '7', 'Wash Bertomieu', 'All Tomorrow''s Parties', 'Down-sized', 2, 'Documentary|Musical', 'Runte, Wolff and O''Keefe', 2013, 'Oriya', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/139x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('346213152-4', '63954', 'Leanora Plumbridge', 'Lone Ranger, The', 'Cross-group', 5, 'Adventure|Western', 'Berge-Ritchie', 2006, 'Hungarian', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/207x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('413862210-1', '0', 'Fabe Kilborn', 'Girl, The', 'concept', 8, 'Drama', 'Feeney, Lowe and Hilpert', 1997, 'Māori', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('910286062-7', '7298', 'Temp Ruby', 'Misery', 'encryption', 8, 'Drama|Horror|Thriller', 'Fisher LLC', 1999, 'Gujarati', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/190x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('576623300-0', '1272', 'Tallia Siddele', 'Being John Malkovich', 'analyzing', 2, 'Comedy|Drama|Fantasy', 'Purdy Inc', 1996, 'Lithuanian', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/247x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('357393662-8', '2', 'Flori Wheway', 'Normal Adolescent Behavior', 'Reverse-engineered', 9, 'Drama|Romance', 'Funk-Torp', 2011, 'Afrikaans', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/240x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('112745500-1', '466', 'Rudd Brede', 'There''s Something About Mary', 'disintermediate', 8, 'Comedy|Romance', 'Goyette-Langosh', 2013, 'Malay', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/114x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('767206275-1', '92', 'Kenny Bedwell', 'Angry Silence, The', 'matrix', 9, 'Drama', 'Schaden-Hartmann', 2010, 'Tamil', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'http://dummyimage.com/223x100.png/cc0000/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('125628189-1', '3', 'Logan Moohan', 'Operación Cannabis', 'Networked', 2, 'Action|Adventure|Comedy|Crime', 'Hintz-Leffler', 1994, 'Assamese', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('413729420-8', '2838', 'Valerie Attack', 'Game of Death', 'Ergonomic', 4, 'Action|Adventure|Thriller', 'Hudson, Conroy and Jones', 2001, 'Macedonian', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('010607973-5', '554', 'Jolynn Spiaggia', 'The Ghost Story of Oiwa''s Spirit', 'alliance', 7, 'Horror', 'Stamm and Sons', 1996, 'Afrikaans', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('922460458-7', '76', 'Minor Pavlovsky', 'Broken English', 'interactive', 8, 'Drama', 'Bergnaum, Hettinger and Schmidt', 1997, 'Korean', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/104x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('623301884-6', '649', 'Vyky D''Antuoni', 'Planes: Fire & Rescue', 'explicit', 1, 'Adventure|Animation|Comedy', 'Farrell Inc', 2007, 'New Zealand Sign Language', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/238x100.png/ff4444/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('705518220-4', '022', 'Roscoe Iwanicki', 'Northern Lights', 'zero administration', 2, 'Drama|Mystery|Romance', 'Doyle-Ankunding', 1986, 'Sotho', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/149x100.png/dddddd/000000');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('692227604-3', '0985', 'Archambault Cureton', 'A Cinderella Story: Once Upon a Song', 'internet solution', 3, 'Children|Comedy|Romance', 'Zboncak-Torp', 2010, 'Maltese', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff');
insert into Book (ISBN, author_id, author_name, book_name, title, edition, genre, publisher_name, year_published, language, synopsis, image) values ('203259576-1', '77888', 'Correna Klemz', 'Flesh and the Devil', 'alliance', 10, 'Drama|Romance', 'Batz-Kiehn', 2003, 'Kurdish', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'http://dummyimage.com/187x100.png/ff4444/ffffff');
