insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('776541141-1', '82', 'Welch MacTerrelly', 'Tulpan', 'Enhanced maximized projection', 7, 'Comedy|Drama', 'Nitzsche, Vandervort and Aufderhar', 2008, 'Chinese', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/200x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('160414665-6', '86069', 'Clarey Krink', 'Drei Stunden', 'Distributed background help-desk', 7, 'Comedy|Romance', 'Jones Group', 1992, 'West Frisian', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/167x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('727455387-9', '4', 'Mureil Allward', 'Heiress, The', 'Integrated context-sensitive leverage', 5, 'Drama|Romance', 'Bergnaum Group', 1984, 'Dutch', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/218x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('648965640-X', '8', 'Gladys Coard', 'Fuse (Gori vatra)', 'Synergized tertiary projection', 3, 'Comedy|Drama', 'Douglas LLC', 2008, 'Kazakh', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('265773952-0', '665', 'Johny Manwell', '200 M.P.H.', 'Seamless 24/7 contingency', 5, 'Action|Adventure|Drama', 'Daugherty, Denesik and Larkin', 1998, 'Macedonian', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/222x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('396114063-4', '4', 'Reube Izakovitz', 'Stateside', 'Extended tertiary installation', 1, 'Drama', 'Denesik, Rolfson and Hills', 2012, 'Bislama', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/126x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('285708263-0', '82', 'Tamara Langfitt', 'Diary of a Chambermaid, The', 'Optimized fault-tolerant access', 1, 'Drama|Romance', 'Becker-Bins', 1989, 'Aymara', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/148x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('787093433-X', '18868', 'Holly-anne Goalley', 'The Taking of Deborah Logan', 'Multi-lateral next generation solution', 7, 'Horror|Thriller', 'Bashirian, Nicolas and Hilll', 2005, 'Malagasy', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/221x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('632793151-0', '09276', 'Orlan Anfossi', 'India (Indien)', 'Versatile optimal open architecture', 6, 'Comedy|Drama', 'Mueller and Sons', 1993, 'Pashto', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('157614211-6', '1937', 'Thorpe Jozwiak', 'My Way (Mai Wei)', 'Synergistic attitude-oriented approach', 7, 'Action|Drama|War', 'Lynch Group', 1990, 'Quechua', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('671106294-9', '22776', 'Birgitta Domenc', 'Ben-Hur', 'Expanded uniform artificial intelligence', 9, 'Action|Adventure|Drama', 'Beahan Group', 1993, 'West Frisian', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/169x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('652777440-0', '06', 'Nilson Rolph', 'Vitus', 'Organic tangible help-desk', 6, 'Drama', 'Abernathy Inc', 1999, 'Afrikaans', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/210x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('879959517-6', '5183', 'Bernie Signore', 'Mother, I Love You', 'Devolved high-level productivity', 7, 'Drama', 'McCullough, Hamill and Sipes', 1994, 'Luxembourgish', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/166x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('792054838-1', '1962', 'Jamill Coultous', 'Wheel of Time', 'Ergonomic static structure', 10, 'Documentary', 'Gottlieb Group', 1993, 'Aymara', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/103x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('939912868-7', '38278', 'Jennine Jarrell', 'Oliver & Company', 'Public-key web-enabled project', 5, 'Adventure|Animation|Children|Comedy|Musical', 'Schimmel Group', 2002, 'New Zealand Sign Language', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('767204835-X', '6448', 'Clevie Dmitriev', 'Band of the Hand', 'Innovative 24/7 Graphic Interface', 1, 'Action|Crime|Drama', 'Hartmann Group', 2004, 'Spanish', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('880000636-1', '425', 'Rhona Bostock', 'Vacuum-Cleaner Salesmen (Pölynimurikauppiaat)', 'Polarised directional product', 9, 'Documentary', 'Harris and Sons', 2006, 'West Frisian', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/234x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('758616790-7', '74880', 'Patsy Fishwick', 'McLibel', 'Proactive analyzing capacity', 5, 'Documentary', 'Kirlin-Barrows', 1996, 'Amharic', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'http://dummyimage.com/124x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('839372411-2', '272', 'Marylee Tewkesberrie', 'Boulevard', 'Optional asynchronous conglomeration', 1, 'Crime|Drama', 'Harvey, Beatty and Brown', 1991, 'Kazakh', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/138x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('983905225-X', '17', 'Caspar Newlove', 'Making the Earth Stand Still', 'Cross-platform demand-driven customer loyalty', 4, 'Documentary', 'Wiegand Group', 2012, 'Kazakh', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/128x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('148759822-X', '97361', 'Howey Audiss', 'Judgment in Berlin', 'Up-sized transitional budgetary management', 4, 'Crime|Drama', 'Wilkinson, Little and Kovacek', 1970, 'Thai', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.

Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/124x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('957368111-0', '67411', 'Efren Pristnor', 'Clay Bird, The (Matir moina)', 'Automated mobile Graphic Interface', 3, 'Drama', 'Mayert-Bernier', 2012, 'Tok Pisin', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.

Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('287624975-8', '3047', 'Maddy Claypool', 'Return to Salem''s Lot, A', 'Up-sized composite flexibility', 7, 'Horror', 'Fay-Dibbert', 2011, 'Hebrew', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/142x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('045959641-1', '2660', 'Esther Jaram', 'Tyler Perry''s Diary of a Mad Black Woman', 'Organic multi-tasking toolset', 7, 'Comedy|Drama|Romance', 'Hettinger-Bruen', 1987, 'Bengali', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/214x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('388260831-5', '29', 'Kati Sandcraft', 'Catwoman', 'Integrated 6th generation local area network', 8, 'Action|Crime|Fantasy', 'Abbott, Brakus and Considine', 1997, 'Portuguese', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/246x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('953189201-6', '23', 'Fergus Gatman', 'Errors of the Human Body ', 'Streamlined modular complexity', 5, 'Drama|Sci-Fi|Thriller', 'Kris-Rutherford', 2010, 'Dhivehi', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/187x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('573666912-9', '51', 'Reginauld Arnett', 'Alice Doesn''t Live Here Anymore', 'Self-enabling leading edge access', 6, 'Drama|Romance', 'Schoen-Morar', 2002, 'Kannada', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/172x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('414222611-8', '3', 'Irita Cambell', 'Berlin Babylon', 'Mandatory hybrid frame', 7, 'Documentary', 'Jenkins, Jones and Kub', 1995, 'Bulgarian', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/194x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('804503816-0', '22', 'Cristian Helkin', 'In the Shadow of the Machine', 'Digitized 6th generation budgetary management', 7, 'Documentary', 'Mosciski-Nader', 1997, 'French', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'http://dummyimage.com/189x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('897113309-0', '433', 'Rafael Tolliday', 'Santa''s Apprentice', 'Progressive optimizing software', 9, 'Animation|Children', 'Hilpert Group', 1992, 'Finnish', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('670913778-3', '7342', 'Peri Hatliff', '20 Million Miles to Earth', 'Balanced neutral open system', 7, 'Sci-Fi', 'Wunsch-Waters', 1993, 'Irish Gaelic', 'Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/232x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('703749173-X', '0459', 'Mollie Beckhurst', 'My Son (Mon fils à moi)', 'Networked bandwidth-monitored flexibility', 4, 'Drama', 'Bernhard-Harvey', 2011, 'Hindi', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('492458550-5', '8226', 'Hastings Postill', 'It Rains in My Village (Bice skoro propast sveta)', 'Quality-focused disintermediate website', 10, 'Drama', 'Reinger-Bernhard', 2007, 'Malayalam', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('745038510-4', '3', 'Burton Lay', 'One Percent, The', 'Switchable dynamic task-force', 8, 'Documentary', 'Heller and Sons', 1987, 'Portuguese', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/126x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('826332863-2', '2', 'Benjamin Padgham', 'JCVD', 'Mandatory homogeneous utilisation', 3, 'Action|Drama|Thriller', 'Schinner-Lakin', 1994, 'Arabic', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'http://dummyimage.com/241x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('710627652-9', '654', 'Kitty Parsonage', 'That Was Then... This Is Now', 'Cross-group analyzing migration', 3, 'Drama', 'Cremin-Bartell', 2010, 'Kazakh', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/247x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('267577753-6', '18532', 'Mallory Chicco', 'Boy Meets Boy', 'Customizable multimedia orchestration', 6, 'Romance', 'Schinner-Glover', 2006, 'Hebrew', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/216x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('940076176-7', '910', 'Delmore Streat', 'Sea Wife', 'Triple-buffered dedicated service-desk', 9, 'Drama|Romance', 'Goldner, Kutch and Barrows', 1992, 'Malayalam', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('897661871-8', '5654', 'Rourke Labdon', 'Enforcer, The', 'Seamless fault-tolerant help-desk', 1, 'Crime|Drama|Film-Noir', 'Kautzer, Torphy and Littel', 2006, 'Romanian', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.

Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/206x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('200327819-2', '7316', 'Reid O''Heaney', 'Callejón de los milagros, El', 'Cloned optimizing approach', 10, 'Drama', 'Hegmann, Gaylord and Keeling', 2007, 'Armenian', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/179x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('769985947-2', '126', 'Marylynne Stiant', 'Mad Love', 'Customer-focused hybrid matrices', 10, 'Drama|Romance', 'Pagac Inc', 1994, 'Lithuanian', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/202x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('778241233-1', '0140', 'Kristine Kitman', 'Vesku from Finland (Vesku)', 'Devolved content-based knowledge base', 7, 'Documentary', 'Herman, Kassulke and Roob', 1992, 'Estonian', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/228x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('301280670-9', '002', 'Odella Featherbie', 'Curse of Chucky (Child''s Play 6)', 'Synchronised bifurcated focus group', 1, 'Horror|Thriller', 'Denesik-Kiehn', 2006, 'Dutch', 'In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/184x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('715894241-4', '0', 'Boycey Shaves', 'Legend, The (Legend of Fong Sai-Yuk, The) (Fong Sai Yuk)', 'Profit-focused stable access', 5, 'Action|Comedy', 'Tremblay-Rosenbaum', 2003, 'Hiri Motu', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/212x100.png/5fa2dd/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('560920930-7', '69229', 'Dukie Serle', 'Good Old Daze (Le péril jeune)', 'Ameliorated leading edge hardware', 6, 'Comedy|Drama', 'Raynor-Schimmel', 1990, 'Danish', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/143x100.png/cc0000/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('901166535-X', '236', 'Frants Vasyukov', 'Autumn in New York', 'Intuitive multimedia functionalities', 2, 'Drama|Romance', 'McLaughlin, Kuvalis and Macejkovic', 1992, 'Tok Pisin', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/213x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('528181222-X', '870', 'Carolynn Sydry', 'World''s Greatest Lover, The', 'Profound even-keeled installation', 4, 'Comedy', 'Stehr, Wuckert and Kuhlman', 2008, 'Kannada', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/150x100.png/dddddd/000000');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('817068004-2', '00090', 'Luisa Bradford', 'Lesson of the Evil (Aku no kyôten)', 'Devolved 4th generation infrastructure', 4, 'Thriller', 'Considine, Ankunding and Smitham', 2012, 'Hungarian', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/212x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('028792931-0', '7794', 'Rafe Rogger', 'Running Scared', 'Diverse 24/7 matrix', 8, 'Action|Comedy', 'West, Metz and Bosco', 1993, 'Northern Sotho', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/139x100.png/ff4444/ffffff');
insert into book (ISBN, author_id, author_name, book_name, title, edition, category/genre, publisher_name, year_published, language, synopsis, image) values ('827971254-2', '5', 'Norbert McAster', 'Duma', 'Intuitive web-enabled parallelism', 9, 'Adventure|Drama', 'Anderson Group', 2008, 'Zulu', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'http://dummyimage.com/158x100.png/ff4444/ffffff');
